name: Deploy on staging

on:
  push:
    branches:
      - "main"

jobs:
  redeploy_everything:
    name: Deploying everything to the staging cluster
    runs-on: ubuntu-latest

    steps:
      - name: SSH Into server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@64.227.247.124 << 'EOF'
            cd week-25-ci-next-app/ && git pull 
            pnpm install 
            pnpm run build 
            pm2 restart fe-server
            pm2 restart http-server
            pm2 restart ws-server
          EOF
